//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
//" Script Title       : 
//" Script Description : 
//"                      
//"                      
//" Script Author      : njfranco
//" Script Date        : Tue Aug 14 12:16:13 2018
//" Generated By       : LoadRunner Recorder (Build: 1203)
//"'''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''

function vuser_init()
{
	return 0;
}

